apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-ai-config
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: cluster-config
    tenant: composer-ai
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: appOfApps
    repoURL: 'https://github.com/redhat-composer-ai/appOfApps.git'
    targetRevision: modelcar
    helm:
      parameters:
        - name: gitops.namespace
          value: composer-ai-gitops
        - name: application.defaultNamespace
          value: composer-ai-apps
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/source/repoURL
        - /spec/source/targetRevision
